name: Publish to PyPI

on: workflow_dispatch

jobs:

  build-and-publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Check out the Repository
      uses: actions/checkout@v3
    
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel requests twine

    - name: Set Environment Variable
      run: |
        lcflib_version=$(python -c "import LCFLib; print(LCFLib.__version__)")
        echo "LCFLIB_VERSION=lcflib_version" >> $GITHUB_ENV

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

    - name: Rename file
      run: |
        mv dist/*.whl dist/LoCyanFrpLib-${{ env.LCFLIB_VERSION }}-py${{ matrix.python-version }}-none-any.whl
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Python${{ matrix.python-version }}-LoCyanFrpLib${{ env.LCFLIB_VERSION }}
        path: dist/
  
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*.whl

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ./ChangeLog.md
        prerelease: false
        draft: false
        tag_name: v${{ env.LCFLIB_VERSION }}
        files: |
          dist/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}