name: Publish to PyPI

on: workflow_dispatch

jobs:

  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Check out the Repository
      uses: actions/checkout@v3
    
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel requests twine

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

    - name: Set Environment Variable
    run: |
      lcflib_version=$(python -c "import LCFLib; print(LCFLib.__version__)")
      echo "LCFLIB_VERSION=$lcflib_version" >> $GITHUB_ENV

    - name: Rename file
      run: |
        mv dist/*.whl dist/LCFLib-${{ env.LCFLIB_VERSION }}-py${{ matrix.python-version }}-none-any.whl
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Python-${{ matrix.python-version }}-LCFLib-v${{ env.LCFLIB_VERSION }}
        path: dist/
  
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*.whl

  Release:
    runs-on: ubuntu-latest

    needs:
      - Build

    steps:

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Asia/Shanghai'

      - name: Install Tools
        run: sudo apt install p7zip-full -y

      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          lcflib_version=$(python -c "import LCFLib; print(LCFLib.__version__)")
          echo "LCFLIB_VERSION=$lcflib_version" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./ChangeLog.md
          prerelease: false
          draft: false
          tag_name: v${{ env.LCFLIB_VERSION }}
          files: |
            Python-3.7-LCFLib-v${{ env.LCFLIB_VERSION }}
            Python-3.8-LCFLib-v${{ env.LCFLIB_VERSION }}
            Python-3.9-LCFLib-v${{ env.LCFLIB_VERSION }}
            Python-3.10-LCFLib-v${{ env.LCFLIB_VERSION }}
            Python-3.11-LCFLib-v${{ env.LCFLIB_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}